export const describesYourPlace = {
    House: 'House',
    Apartment: 'Apartment',
    Barn: 'Barn',
    BedAndBreakfast: 'Bed And Breakfast',
    Boat: 'Boat',
    Cabin: 'Cabin',
    Castle: 'Castle',
    Cave: 'Cave',
    Container: 'Container',
    CycladicHome: 'Cycladic home',
    Dammuso: 'Dammuso',
    Dome: 'Dome',
    EarthHome: 'Earth home',
    Villa: 'Villa',
    Guesthouse: 'Guesthouse',
    Hotel: 'Hotel',
    Houseboat: 'Houseboat',
    Kezhan: 'Kezhan',
    Minsu: 'Minsu',
    Ryokan: 'Ryokan',
    Tent: 'Tent',
    TinyHome: 'Tiny home',
    Tower: 'Tower',
};
